### ISSUE TITLE
Error in stage [fr.davit.akka.http.metrics.core.MeterStage$$anon$1-MeterStage]: No value present

### ISSUE THREAD

**Issue by zzvara** [RustedBones/akka-http-metrics#117]
AKKA 2.6.13 with HTTP 10.2.4 & Scala 2.12.12.

Error:

```
2021-03-27 14:56:38.315 ERROR [t-dispatcher-18] r$$anonfun$receive$1: Error in stage [fr.davit.akka.http.metrics.core.MeterStage$$anon$1-MeterStage]: No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:148) ~[?:?]
	at fr.davit.akka.http.metrics.core.MeterStage$$anon$1$$anon$3.onPush(MeterStage.scala:76) ~[akka-http-metrics-core_2.12-1.5.1.jar:1.5.1]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:773) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:788) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) ~[akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) ~[akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691) ~[akka-stream_2.12-2.6.13.jar:2.6.13]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577) [akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [akka-actor_2.12-2.6.13.jar:2.6.13]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [akka-actor_2.12-2.6.13.jar:2.6.13]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

Debug path with some data:

![image](https://user-images.githubusercontent.com/8371789/112723729-4a13ea80-8f10-11eb-8d1f-566f4e62069b.png)

![image](https://user-images.githubusercontent.com/8371789/112723363-5bf48e00-8f0e-11eb-8c05-e3eb07790aa3.png)

![image](https://user-images.githubusercontent.com/8371789/112723369-63b43280-8f0e-11eb-870b-c2fc73ec7486.png)

Application code:

![image](https://user-images.githubusercontent.com/8371789/112723433-bf7ebb80-8f0e-11eb-8d89-198eeade8c7e.png)

All non-WS paths work properly.
This is how the application binds:
```
val bindingFuture =
            portBind.prometheusRegistry
              .map(Http().newMeteredServerAt(portBind.host, port, _))
              .getOrElse(Http().newServerAt(portBind.host, port))
              .bindFlow(
                if (portBind.secureConfiguration.isDefined) redirectHandler
                else portBind.handler
              )
```

**Comment by zzvara** [comment]
@RustedBones thanks for looking into it. I checked and we refactored the handler as follows:

`HttpMetrics.metricsRouteToFlow(controller.route)`

There was a problem around that, it works now. I think it was a problem with our application code, we somehow initialized the whole port-binder and handler incorrectly.

**Comment by RustedBones** [comment]
Thanks for the feedback.
It seems to be an implicit conflict then. The `metricsRouteToFlow` wasn't preferred over the default akka implicit transformation of the routes.

**Comment by aaabramov** [comment]
Just to clarify things out:

```scala
Http()
  .newMeteredServerAt("0.0.0.0", 9000, registry)
  .bindFlow(routes)
```

should be replaced with 

```scala
import fr.davit.akka.http.metrics.core.HttpMetrics
import fr.davit.akka.http.metrics.core.HttpMetrics.enrichHttp

Http()
  .newMeteredServerAt("0.0.0.0", 9000, registry)
  .bindFlow(HttpMetrics.metricsRouteToFlow(routes)) // <= make explicit conversion
```

**Comment by zzvara** [comment]
@aaabramov yes we solved it with explicit conversion!

**Comment by aaabramov** [comment]
Shouldn't we update the README then? Because if not this issue I would spend hours what's wrong )

**Comment by zzvara** [comment]
@aaabramov I think it definitely worths a shot. Alternatively:

```
java.util.NoSuchElementException: No value present
```

Should be catching and wrapped into a more descriptive exception that may even contain 500 characters long help:

"This error may suggest that you forgot the explicitly convert your route ..."

**Comment by aaabramov** [comment]
@zzvara I can give it a shot.

**Comment by RustedBones** [comment]
I see where the confusion comes from.
In all my example, everything works as expected because of the import bringing the implicit conversion
```scala
import fr.davit.akka.http.metrics.core.HttpMetrics._
```
I'll deprecate the implicitin favor of the explicit.
I also like @zzvara idea to create a more informative exception in case of missing the `track-id`

**Comment by aaabramov** [comment]
@RustedBones I am currently working on informative exception. Will submit PR in ~ 30 minutes
