### ISSUE TITLE
Getting error when using bindFlow : `.Error in stage [fr.davit.akka.http.metrics.core.MeterStage$$anon$1-MeterStage]: No value present

### ISSUE THREAD

**Issue by bguthro** [RustedBones/akka-http-metrics#186]
Hello, 
I'm getting the following stack, when trying to use the v1.5.1 in the following manner:

```
object Metrics {
      import akka.util.Timeout
      import fr.davit.akka.http.metrics.core.scaladsl.server.HttpMetricsDirectives.metrics
      import fr.davit.akka.http.metrics.prometheus.marshalling.PrometheusMarshallers._
      import fr.davit.akka.http.metrics.prometheus.{Buckets, PrometheusRegistry, PrometheusSettings, Quantiles}
      import io.prometheus.client.CollectorRegistry

      class ClusterMetricsRouter(implicit context : ActorRefFactory, timeout : Timeout) {
        import ClusterMetricsRouter._

        implicit val _ = Implicits.system
        implicit val executionContext = context.dispatcher

        val route : Route = {
          metrics(ClusterMetricsRouter.registry)
        }

        val internal_route : Route = {
          metrics(ClusterMetricsRouter.internal_registry)
        }
      }
      object ClusterMetricsRouter {
        private val settings: PrometheusSettings = PrometheusSettings
          .default
          .withIncludePathDimension(true)
          .withIncludeMethodDimension(true)
          .withIncludeStatusDimension(true)
          .withDurationConfig(Buckets(1, 2, 3, 5, 8, 13, 21, 34))
          .withReceivedBytesConfig(Quantiles(0.5, 0.75, 0.9, 0.95, 0.99))
          .withSentBytesConfig(PrometheusSettings.DefaultQuantiles)
          .withDefineError(_.status.isFailure)

        private val collector: CollectorRegistry = CollectorRegistry.defaultRegistry

        val registry: PrometheusRegistry = PrometheusRegistry(collector, settings)
    }
}

...

def routeWithClose(route : Future[akka.Done] => Route) : Flow[HttpRequest, HttpResponse, Any] = {
      import akka.http.scaladsl.server
      Flows.lazyFlow { () =>
        val p = Promise[akka.Done]()
        server.Route.toFlow(route(p.future)).watchTermination() { case (mat, done) =>
          p.completeWith(done)
          mat
        }
      }
    }

 ...

Http()
          .newMeteredServerAt(
            "0.0.0.0",
            8443,
            Routes.Metrics.ClusterMetricsRouter.registry
          )
          .enableHttps(ConnectionContext.httpsServer(ssl))
          .bindFlow(routeWithClose(done => Routes.route(done)))
```

I'm using an older release because of this issue, since I need `.bindFlow` above.
https://github.com/RustedBones/akka-http-metrics/issues/184

However - this throws the following stack:
```
2021-11-01T21:20:37.641+00:00 | ERROR | default-akka.actor.default-dispatcher-12 | akka.actor.RepointableActorRef | Error in stage [fr.davit.akka.http.metrics.core.MeterStage$$anon$1-MeterStage]: No value present |
"" | java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Optional.java:141)
        at fr.davit.akka.http.metrics.core.MeterStage$$anon$1$$anon$3.onPush(MeterStage.scala:76)
        at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:542)
        at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:496)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
        at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$shortCircuitBatch(ActorGraphInterpreter.scala:787)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:819)
        at akka.actor.Actor.aroundReceive(Actor.scala:537)
        at akka.actor.Actor.aroundReceive$(Actor.scala:535)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
        at akka.actor.ActorCell.invoke(ActorCell.scala:548)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
        at akka.dispatch.Mailbox.run(Mailbox.scala:231)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

Is there some setup that I'm missing from the above? Equivalent code works elsewhere, when not using the `.bindFlow`

I'm hoping that this is a user error, and you can point me to something I'm doing wrong in my code to resolve the issue?

**Comment by RustedBones** [comment]
Can this [answer](https://github.com/RustedBones/akka-http-metrics/issues/184#issuecomment-958927923) help when using `bindFlow` ? (Using the `meterFlow`)

```scala
val meteredFlow = HttpMetrics.meterFlow(metricsHandler).join(flow)
Http.newSeverAt(host,port).bindFlow(meteredFlow)
```

**Comment by RustedBones** [comment]
Since last comment has not been answered, I'll close the ticket.
Feel free to reopen you are still facing the issue
