### ISSUE TITLE
Getting exception when StatusDimension or PathDimension is true (prometheus)

### ISSUE THREAD

**Issue by k7i3** [RustedBones/akka-http-metrics#45]
```
scala = 2.13
akka-http-metrics-prometheus = 0.6.0
akka-stream = 2.5.25
akka-http = 10.1.9

val settings: HttpMetricsSettings = HttpMetricsSettings
      .default
      .withIncludeStatusDimension(true)
      .withIncludePathDimension(true)
val registry: PrometheusRegistry = PrometheusRegistry(settings)

val bindingFuture = Http().bindAndHandle(route.recordMetrics(registry), "localhost", 8080)
```

after any request:

```
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
 at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
 at akka.http.impl.util.One2OneBidiFlow$OutputTruncationException$.apply(One2OneBidiFlow.scala:22)
 at akka.http.impl.util.One2OneBidiFlow$One2OneBidi$$anon$1$$anon$4.onUpstreamFinish(One2OneBidiFlow.scala:97)
 at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:506)
 at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:376)
 at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
 at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
 at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
 at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
 at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
 at akka.actor.Actor.aroundReceive(Actor.scala:539)
 at akka.actor.Actor.aroundReceive$(Actor.scala:537)
 at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
 at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
 at akka.actor.ActorCell.invoke(ActorCell.scala:581)
 at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
 at akka.dispatch.Mailbox.run(Mailbox.scala:229)
 at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
 at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
 at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
 at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
 at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
if remove 

```
.withIncludeStatusDimension(true)
.withIncludePathDimension(true)
```
then everything ok

**Comment by RustedBones** [comment]
Hi @k7i3 

Thanks for reporting.
Prometheus registry implementation needs `settings` to be passed in `recordMetrics`. See #36 .

This is fixed in upcoming release.
