### ISSUE TITLE
Bug 1.4.0: java.lang.IllegalArgumentException: requirement failed: Responses with this status code must have an empty entity

### ISSUE THREAD

**Issue by zzvara** [RustedBones/akka-http-metrics#80]
Upon upgrading to 1.4.0 with Scala Steward, 6 out of our 504 automatically fail due to:

```
java.lang.IllegalArgumentException: requirement failed: Responses with this status code must have an empty entity
	at scala.Predef$.require(Predef.scala:281) ~[scala-library.jar:?]
	at akka.http.scaladsl.model.HttpResponse.<init>(HttpMessage.scala:515) ~[akka-http-core_2.12-10.2.2.jar:10.2.2]
	at akka.http.scaladsl.model.HttpResponse.copyImpl(HttpMessage.scala:565) ~[akka-http-core_2.12-10.2.2.jar:10.2.2]
	at akka.http.scaladsl.model.HttpResponse.transformEntityDataBytes(HttpMessage.scala:549) ~[akka-http-core_2.12-10.2.2.jar:10.2.2]
	at fr.davit.akka.http.metrics.core.HttpMetricsRegistry.onResponse(HttpMetricsRegistry.scala:146) ~[akka-http-metrics-core_2.12-1.4.0.jar:1.4.0]
	at fr.davit.akka.http.metrics.core.MeterStage$$anon$1$$anon$3.onPush(MeterStage.scala:78) ~[akka-http-metrics-core_2.12-1.4.0.jar:1.4.0]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:541) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:423) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:625) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:502) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:600) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:769) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:784) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.actor.Actor.aroundReceive(Actor.scala:537) ~[akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.actor.Actor.aroundReceive$(Actor.scala:535) ~[akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:691) ~[akka-stream_2.12-2.6.10.jar:2.6.10]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577) [akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.actor.ActorCell.invoke(ActorCell.scala:547) [akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270) [akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.dispatch.Mailbox.run(Mailbox.scala:231) [akka-actor_2.12-2.6.10.jar:2.6.10]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:243) [akka-actor_2.12-2.6.10.jar:2.6.10]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]

```

We create socket connections as:

```
pathLabeled("channel") {
                get {
                  handleWebSocketMessages(
                    fConversationFactory()
                      .socketForChat(chatID, kind)
                  )
                }
              } ~
```

Above that we have a `pathPrefixLabeled` and so on.

**Comment by RustedBones** [comment]
Thanks for reporting the regression @zzvara.
The new implementation always transforms requests and responses data into streams to collect metrics. Seems that in some cases the framework expects to have ab empty **strict** instead of an empty streamed entity.
I'll create a patch so that strict entities are processed without transformation.

**Comment by RustedBones** [comment]
@zzvara is that fixed with release 1.4.1?

**Comment by zzvara** [comment]
@RustedBones running on CI.

**Comment by zzvara** [comment]
@RustedBones all tests (`akka-http` 300 out of 520) succeed, all routes use `akka-http-metrics`, including web-sockets.

Thanks! Due to our CI, I will be probably the first to report problems here. :-)

**Comment by RustedBones** [comment]
Great. Having caught the regression just after the release with your CI is super valuable. It will avoid breaking prod for other users.
Thanks again for reporting this so quickly and kudos for the good testing.
